# Generated by Django 2.2.1 on 2019-08-17 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('type_shope', models.CharField(choices=[('men clothing', 'MC'), ('women clothes', 'WC'), ('Informatique', 'IN'), ('furniture', 'FU'), ('cosmetic', 'CO')], max_length=5)),
                ('num_phone', models.CharField(max_length=10)),
                ('wilaya', models.CharField(choices=[('Adrar', '1'), ('Chelf', '2'), ('Laghouat', '3'), ('Oum El Bouaghi', '4'), ('Batna', '5'), ('Béjaïa', '6'), ('Biskra', '7'), ('Béchar', '8'), ('Blida', '9'), ('Bouira', '10'), ('Tamanrasset', '11'), ('Tébessa', '12'), ('Tlemcen', '13'), ('Tiaret', '14'), ('Tizi Ouzou', '15'), ('Alger', '16'), ('Djelfa', '17'), ('Jijel', '18'), ('Sétif', '19'), ('Saïda', '20'), ('Skikda', '21'), ('Sidi Bel Abbès', '22'), ('Annaba', '23'), ('Guelma', '24'), ('Constantine', '25'), ('Médéa', '26'), ('Mostaganem', '27'), ("M'Sila", '28'), ('Mascara', '29'), ('Ouargla', '30'), ('Oran', '31'), ('El Bayadh', '32'), ('Illizi', '33'), ('Bordj Bou Arreridj', '34'), ('Boumerdès', '35'), ('El Tarf', '36'), ('Tindouf', '37'), ('Tissemsilt', '38'), ('El Oued', '39'), ('Khenchela', '40'), ('Souk Ahras', '41'), ('Tipaza', '42'), ('Mila', '43'), ('Aïn Defla', '44'), ('Naâma', '45'), ('Aïn Témouchent', '46'), ('Ghardaïa', '47'), ('Relizane', '48')], max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.FileField(default='logo/default.png', upload_to='logo/', verbose_name='')),
                ('bill', models.FileField(upload_to='bill/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
