# Generated by Django 2.2.1 on 2019-08-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20190817_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shope',
            name='num_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shope',
            name='type_shope',
            field=models.CharField(choices=[('MC', 'men clothing'), ('WC', 'women clothes'), ('IN', 'Informatique'), ('FU', 'furniture'), ('CO', 'cosmetic')], max_length=25),
        ),
        migrations.AlterField(
            model_name='shope',
            name='wilaya',
            field=models.CharField(choices=[('1', 'Adrar'), ('2', 'Chelf'), ('3', 'Laghouat'), ('4', 'Oum El Bouaghi'), ('5', 'Batna'), ('6', 'Béjaïa'), ('7', 'Biskra'), ('8', 'Béchar'), ('9', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arreridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane')], max_length=50),
        ),
    ]
