# Generated by Django 2.2.1 on 2019-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20190817_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shope',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
