# Generated by Django 2.2.1 on 2019-08-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20190817_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shope',
            name='bill',
            field=models.FileField(default='logo/default.png', upload_to='bill/'),
        ),
    ]
