# Generated by Django 2.2.1 on 2019-08-17 23:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20190818_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='image'), size=5),
        ),
    ]
