# Generated by Django 2.2.1 on 2019-08-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20190818_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_buy',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('products', models.ManyToManyField(to='seller.Product')),
                ('shope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Shope')),
            ],
        ),
    ]
