# Generated by Django 2.2.1 on 2019-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_auto_20190818_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_field',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
