# Generated by Django 2.2.1 on 2019-08-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_product_add_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='date',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='products',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='total_price',
        ),
        migrations.AddField(
            model_name='buy',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='idd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='first_images',
            field=models.FileField(default='logo/default.png', upload_to='image', verbose_name=''),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buys', models.ManyToManyField(to='seller.Buy')),
                ('shope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Shope')),
            ],
        ),
    ]
