# Generated by Django 2.2.1 on 2019-08-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_auto_20190819_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shope',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
