# Generated by Django 2.2.1 on 2019-08-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_auto_20190819_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buys',
            field=models.ManyToManyField(blank=True, null=True, to='seller.Buy'),
        ),
    ]
