# Generated by Django 2.2.1 on 2019-08-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_auto_20190819_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
