# Generated by Django 2.2.1 on 2019-08-20 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20190820_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 23, 4, 40, 613783, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
