# Generated by Django 2.2.1 on 2019-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_auto_20190821_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_reduction',
            field=models.BooleanField(default=False),
        ),
    ]
